# typed: true
# frozen_string_literal: true

# This file is generated by scripts/generate-brew-formula.sh in
# everstacklabs/everstack. Edit that script, not this file.
class Evs < Formula
  desc "CLI for Everstack - the AI gateway, agents, and sandbox platform"
  homepage "https://everstack.ai"
  version "0.1.45"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/everstacklabs/releases/releases/download/v0.1.45/everstack-darwin-arm64.gz"
      sha256 "9d5597234669b7ce401b2c9537b2c4c931167826e11ca16cb59f8340fa0cf8df"
    end
    on_intel do
      url "https://github.com/everstacklabs/releases/releases/download/v0.1.45/everstack-darwin-amd64.gz"
      sha256 "e5da36928cb8ce764e0567d8f2f2ec230463ec7d7449fc168b9252ef1ac969e6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/everstacklabs/releases/releases/download/v0.1.45/everstack-linux-arm64.gz"
      sha256 "fae02cbf677632e0b97388d6ca48cc59a532a6e8ddfd691f7538e7c13b7bcd11"
    end
    on_intel do
      url "https://github.com/everstacklabs/releases/releases/download/v0.1.45/everstack-linux-amd64.gz"
      sha256 "1199b1f1fc62abfc40d21ad723669e7963f00d381947b0dd56386dad0318f2e2"
    end
  end

  def install
    # The release asset is a bare gzipped binary, so Homebrew's gunzip strategy
    # leaves exactly one decompressed file in the staging dir. Its name tracks
    # the download cache entry rather than the asset name, so find it by glob
    # instead of hardcoding a filename that Homebrew is free to change.
    binary = Dir["*"].find { |f| File.file?(f) && File.size(f).positive? }
    odie "no binary found in the downloaded archive" if binary.nil?

    chmod 0755, binary
    bin.install binary => "evs"

    # Backward-compatible alias for installs predating the evs rename.
    bin.install_symlink bin/"evs" => "everstack"

    # No generate_completions_from_executable here: the root command sets
    # CompletionOptions.DisableDefaultCmd = true, so 'evs completion' does not
    # exist and calling it would fail the install.
  end

  def caveats
    <<~EOS
      Get started:
        evs login
        evs --help

      'everstack' is installed as a backward-compatible alias.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/evs --version")
    assert_match "Everstack", shell_output("#{bin}/evs --help")
  end
end
