# typed: true
# frozen_string_literal: true

# This file is generated by scripts/generate-brew-formula.sh in
# everstacklabs/everstack. Edit that script, not this file.
class Evs < Formula
  desc "CLI for Everstack - the AI gateway, agents, and sandbox platform"
  homepage "https://everstack.ai"
  version "0.1.24"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/everstacklabs/releases/releases/download/v0.1.24/everstack-darwin-arm64.gz"
      sha256 "a4e822851f522bf62496b570ec9ce45ffd08be01341db5d3525eb3e9a888a5b2"
    end
    on_intel do
      url "https://github.com/everstacklabs/releases/releases/download/v0.1.24/everstack-darwin-amd64.gz"
      sha256 "f49c3b3c92357024b8f5b66ebb28b5dd22be631fb4617658b7ab8acd089211ad"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/everstacklabs/releases/releases/download/v0.1.24/everstack-linux-arm64.gz"
      sha256 "2b8417ab80d0e2c0d681b719ad3c35a535a72d924d29301a000ed8172cc9a620"
    end
    on_intel do
      url "https://github.com/everstacklabs/releases/releases/download/v0.1.24/everstack-linux-amd64.gz"
      sha256 "e212face3c32baf481413e4c877312bf57f34bef252b3cd668e9ea8a8b6ba99e"
    end
  end

  def install
    # The release asset is a bare gzipped binary, so Homebrew's gunzip strategy
    # leaves exactly one decompressed file in the staging dir. Its name tracks
    # the download cache entry rather than the asset name, so find it by glob
    # instead of hardcoding a filename that Homebrew is free to change.
    binary = Dir["*"].find { |f| File.file?(f) && File.size(f).positive? }
    odie "no binary found in the downloaded archive" if binary.nil?

    chmod 0755, binary
    bin.install binary => "evs"

    # Backward-compatible alias for installs predating the evs rename.
    bin.install_symlink bin/"evs" => "everstack"

    # No generate_completions_from_executable here: the root command sets
    # CompletionOptions.DisableDefaultCmd = true, so 'evs completion' does not
    # exist and calling it would fail the install.
  end

  def caveats
    <<~EOS
      Get started:
        evs login
        evs --help

      'everstack' is installed as a backward-compatible alias.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/evs --version")
    assert_match "Everstack", shell_output("#{bin}/evs --help")
  end
end
