# typed: true
# frozen_string_literal: true

# This file is generated by scripts/generate-brew-formula.sh in
# everstacklabs/everstack. Edit that script, not this file.
class Evs < Formula
  desc "CLI for Everstack - the AI gateway, agents, and sandbox platform"
  homepage "https://everstack.ai"
  version "0.1.45"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/everstacklabs/releases/releases/download/v0.1.45/everstack-darwin-arm64.gz"
      sha256 "4d838fae0b7276aaad40a854cb01b03ead04ae62226f735c5bba6ef3beab8837"
    end
    on_intel do
      url "https://github.com/everstacklabs/releases/releases/download/v0.1.45/everstack-darwin-amd64.gz"
      sha256 "f41928bd73ff97d4adb2b9f5af5ceb5b99c8cd8edf0a0f589c04fd5b131d4924"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/everstacklabs/releases/releases/download/v0.1.45/everstack-linux-arm64.gz"
      sha256 "d352d01eb39292f4d6da61d25ebbbce1609dae1434e48d8bb72aab54782bde1b"
    end
    on_intel do
      url "https://github.com/everstacklabs/releases/releases/download/v0.1.45/everstack-linux-amd64.gz"
      sha256 "090fd96e3609a977d28b0ae482d44d33799e09304d87354f7a5f51828d9af525"
    end
  end

  def install
    # The release asset is a bare gzipped binary, so Homebrew's gunzip strategy
    # leaves exactly one decompressed file in the staging dir. Its name tracks
    # the download cache entry rather than the asset name, so find it by glob
    # instead of hardcoding a filename that Homebrew is free to change.
    binary = Dir["*"].find { |f| File.file?(f) && File.size(f).positive? }
    odie "no binary found in the downloaded archive" if binary.nil?

    chmod 0755, binary
    bin.install binary => "evs"

    # Backward-compatible alias for installs predating the evs rename.
    bin.install_symlink bin/"evs" => "everstack"

    # No generate_completions_from_executable here: the root command sets
    # CompletionOptions.DisableDefaultCmd = true, so 'evs completion' does not
    # exist and calling it would fail the install.
  end

  def caveats
    <<~EOS
      Get started:
        evs login
        evs --help

      'everstack' is installed as a backward-compatible alias.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/evs --version")
    assert_match "Everstack", shell_output("#{bin}/evs --help")
  end
end
